#!/bin/bash

# Uncomment to use valgrind
#export VALGRIND="valgrind --trace-children=yes --leak-check=full"

# Uncomment to do IO counting
#export IO_COUNT='LD_PRELOAD=$TOILET/io_count.so IO_COUNT_REQUIRE=libtoilet'

# Uncomment to enable patchgroup traces on the tests
#TRACE_TEST="PATCHGROUP_TRACE=test.pgt"
#TRACE_TPCC="PATCHGROUP_TRACE=tpcc.pgt"
#TRACE_DBT2="PATCHGROUP_TRACE=dbt2.pgt"

# Uncomment to enable oprofile
#OPROFILE=oprofile

# Uncomment to use Featherstitch journal mode
#JOURNAL=use_journal=1

if [ -h fstitch ]
then
	FSTYPE="ext2"
	MKFS_ARGS=""
else
	FSTYPE="ext3"
	MKFS_ARGS="-j"
	[ "$TRACE_TEST" -o "$TRACE_TPCC" -o "$TRACE_DBT2" -o \
	  "$JOURNAL" ] && echo "Warning: ignoring Featherstitch-specific option (not using Featherstitch)"
fi

make || exit $?

HOST="`hostname`"
if [ "${HOST#kudos-}" == "$HOST" -a "$HOST" != "execl" -a "$HOST" != "butters" ]
then
	echo "Not running on a kudos-* test machine, won't overwrite your file systems."
	exit 1
fi

if [ "$IO_COUNT" ]
then
	# We use sqlite3 rather than lt-sqlite3 since the latter may not exist yet
	if [ -f .libs/sqlite3 ]
	then
		TOILET="`ldd .libs/sqlite3 | grep /libtoilet.so | sed -e 's/^.*=> \(.*\)\/libtoilet.so .*$/\1/'`"
		if [ ! "$TOILET" ]
		then
			echo "Cannot find toilet; disabling IO counting." >&2
			IO_COUNT=
		fi
	else
		echo "Cannot find .libs/sqlite3; disabling IO counting." >&2
		IO_COUNT=
	fi
fi

if mount | grep -q "on /mnt/test"
then
	echo "/mnt/test is mounted; unmount before running this script."
	exit 1
fi

echo -n "Creating file system... "
sudo mke2fs $MKFS_ARGS -m 0 -b 4096 /dev/sdb1 &> /dev/null
sudo mount /dev/sdb1 /mnt/test -t $FSTYPE
sudo chown -R `whoami` /mnt/test
[ "$JOURNAL" ] && dd if=/dev/zero of=/mnt/test/.journal bs=1M count=64 2> /dev/null
mkdir /mnt/test/journals
echo "done."

if [ "$FSTYPE" == "ext2" ]
then
	sudo umount /mnt/test
	echo -n "Loading Featherstitch... "
	sudo insmod fstitch/kfstitchd.ko device=/dev/sdb || exit $?
	[ -f /proc/kfstitchd_debug ] && (cat /proc/kfstitchd_debug > try.fdb &) || rm -f try.fdb
	sudo mount /mnt/test
	echo "done."
fi

# Run the sqlite test
(WD="`pwd`"; cd /mnt/test; ulimit -c unlimited; eval $IO_COUNT $TRACE_TEST exec $VALGRIND '"$WD/sqlite3"' sql-test) << EOF
create table foo (bar int primary key, baz int);
.explain on
explain insert into foo (bar, baz) values (64, 10);
pragma vdbe_trace=on;
insert into foo (bar, baz) values (64, 10);
insert into foo (bar, baz) values (65, 11);
insert into foo (bar, baz) values (66, 12);
select * from foo;
explain select * from foo where bar=65;
select * from foo where bar=64;
select * from foo where bar=65;
select * from foo where bar=66;
EOF
find /mnt/test -type f -print0 | xargs -0 ls -l

# Create the TPCC tables
(WD="`pwd`"; cd /mnt/test; ulimit -c unlimited; eval $IO_COUNT $TRACE_TPCC exec $VALGRIND '"$WD/sqlite3"' tpcc-empty) < tpcc-create.sql
find /mnt/test -type f -print0 | xargs -0 ls -l

# Run DBT2 loading
if [ -d dbt2/ ]
then
	DBT2_TMP=/tmp/dbt2-sqlite.$$
	BUILD_DB=dbt2/scripts/sqlite/build_db.sh
	# Use -t to disable toilet mode, -T for toilet only mode; these require a patched dbt2
	#MODE=-T
	echo "Running DBT2..."
	mkdir $DBT2_TMP
	if [ "$OPROFILE" ]
	then
		sudo opcontrol --init
		sudo opcontrol --reset
		sudo opcontrol "--vmlinux=/usr/src/linux-`uname -r`/vmlinux"
		sudo opcontrol --start
	fi
	(WD="`pwd`"; cd /mnt/test; ulimit -c unlimited; eval $IO_COUNT $TRACE_DBT2 exec $VALGRIND '"$WD/$BUILD_DB"' $MODE -d sql-dbt2 -f $DBT2_TMP -g -w 1)
	if [ "$OPROFILE" ]
	then
		sudo opcontrol --shutdown
		sudo opcontrol --deinit
		opreport --symbols .libs/lt-sqlite3 > "$OPROFILE"
	fi
	rm -rf $DBT2_TMP
	find /mnt/test -type f -print0 | xargs -0 ls -l
fi

sudo umount /mnt/test
if [ "$FSTYPE" == "ext2" ]
then
	echo "Unloading Featherstitch..."
	time sudo rmmod kfstitchd
fi

echo -ne \\007

sudo mount /dev/sdb1 /mnt/test -t $FSTYPE
rm -f gmon.out* gmon.sum*
if [ -f /mnt/test/gmon.out ]
then
	echo -n "Processing gprof data... "
	cp /mnt/test/gmon.out* .
	for gmon in gmon.out*
	do
		# if there is gmon.out, sqlite3 will be statically linked
		gprof sqlite3 $gmon > ${gmon/out/sum}
	done
	echo "done."
fi
for pgt in /mnt/test/*.pgt
do
	[ "$pgt" == "/mnt/test/*.pgt" ] && break
	echo "Patchgroup trace: `basename "$pgt"`"
	cp "$pgt" .
done
if [ -f /mnt/test/core ]
then
	echo "Starting debugger on core."
	gdb -q -c /mnt/test/core .libs/lt-sqlite3
fi
sudo umount /mnt/test
